"""
Setup and Initialization for Memory Management System
"""

import os
import json
from pathlib import Path


def initialize_system(force: bool = False) -> None:
    """Initialize memory system directory structure and files."""
    
    # Check if already initialized
    if not force and Path("data/.memory.db").exists():
        print("Memory system already initialized. Use --force to reinitialize.")
        return
    
    # Create directory structure
    directories = [
        "data/entries",
        "data/projects",
        "data/decisions",
        "data/logs",
        "data/views",
        "reports/daily",
        "reports/weekly",
        "reports/project",
        "backups",
        "templates",
        "integrations",
        "tests"
    ]
    
    for directory in directories:
        Path(directory).mkdir(parents=True, exist_ok=True)
        print(f"Created: {directory}/")
    
    # Create default config
    create_default_config()
    
    # Create templates
    create_templates()
    
    # Create .gitignore
    create_gitignore()
    
    # Initialize database (will be created on first use)
    print("Database will be created on first use.")
    
    print("\n✓ Memory system initialized successfully!")
    print("\nNext steps:")
    print("  1. Run 'python memory-manager.py entry create' to create your first entry")
    print("  2. Run 'python memory-manager.py project add my-project \"My Project\"' to create a project")
    print("  3. Run 'python memory-manager.py dashboard generate-memory' to generate MEMORY.md")


def create_default_config():
    """Create default configuration file."""
    config = {
        "version": "1.0",
        "database": {
            "path": "data/.memory.db",
            "backup_enabled": True,
            "backup_interval_days": 7,
            "backup_path": "backups/"
        },
        "paths": {
            "entries": "data/entries/",
            "projects": "data/projects/",
            "decisions": "data/decisions/",
            "logs": "data/logs/",
            "reports": "reports/",
            "templates": "templates/"
        },
        "output": {
            "color_enabled": True,
            "date_format": "%Y-%m-%d",
            "datetime_format": "%Y-%m-%d %H:%M",
            "default_view": "table"
        },
        "editor": {
            "default": os.environ.get('EDITOR', 'vim'),
            "template_for_new_entries": "templates/entry_template.md"
        },
        "parsing": {
            "auto_extract_tasks": True,
            "auto_extract_decisions": True,
            "auto_extract_blockers": True,
            "require_approval": True,
            "nlp_backend": "regex"
        },
        "escalation": {
            "enabled": True,
            "levels": [
                {"level": 0, "name": "Identified", "auto_escalate_after_hours": 24},
                {"level": 1, "name": "Acknowledged", "auto_escalate_after_hours": 48},
                {"level": 2, "name": "Escalated", "auto_escalate_after_hours": 72},
                {"level": 3, "name": "Critical", "auto_escalate_after_hours": None}
            ]
        },
        "integrations": {
            "telegram": {
                "enabled": False,
                "bot_token": None
            },
            "openclaw": {
                "enabled": True,
                "auto_parse": True
            }
        }
    }
    
    with open("memory-config.json", 'w') as f:
        json.dump(config, f, indent=2)
    
    print("Created: memory-config.json")


def create_templates():
    """Create default templates."""
    
    # Entry template
    entry_template = """# Daily Log: {{date}}

## Summary

**Title:** {{title}}

**Description:**

**Mood:** /10

**Energy Level:** /10

---

## Tasks

### In Progress
- [ ] 

### Pending
- [ ] 

---

## Decisions

### Today's Decisions

1. **Decision:** 
   - Context: 
   - Alternatives: 
   - Chosen: 

---

## Blockers

- 

---

## Notes

- 

---

## Tags


"""
    
    with open("templates/entry_template.md", 'w') as f:
        f.write(entry_template)
    
    print("Created: templates/entry_template.md")
    
    # Report template
    report_template = """# Report: {{report_type}}

**Generated:** {{timestamp}}

---

{{content}}

---

*Generated by Memory Manager*
"""
    
    with open("templates/report_template.md", 'w') as f:
        f.write(report_template)
    
    print("Created: templates/report_template.md")


def create_gitignore():
    """Create .gitignore file."""
    gitignore = """# Memory System - Generated files
data/.memory.db
*.db-journal
backups/*.db
!backups/.gitkeep

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python

# Virtual environments
venv/
env/
ENV/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"""
    
    with open(".gitignore", 'w') as f:
        f.write(gitignore)
    
    print("Created: .gitignore")
    
    # Create .gitkeep for empty directories
    for directory in ["backups", "reports/daily", "reports/weekly", "reports/project"]:
        Path(f"{directory}/.gitkeep").touch()


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--force', action='store_true', help='Force reinitialization')
    args = parser.parse_args()
    
    initialize_system(force=args.force)
