"""
Dashboard View Generators
"""

import json
from datetime import datetime, timedelta
from typing import List, Dict, Any
from pathlib import Path

from database import Database
from models import Entry, Task, Decision, Blocker, Project
from utils import Colors, format_date, progress_bar


class DashboardUpdater:
    """Update dashboard views and MEMORY.md."""
    
    def __init__(self, database: Database, template_dir: str = "templates/"):
        self.db = database
        self.template_dir = template_dir
    
    def update_all(self) -> None:
        """Update all dashboard views."""
        self.generate_memory_md()
        self.generate_task_view()
        self.generate_decision_view()
        self.generate_blocker_view()
        self.generate_project_view()
    
    def update_view(self, view: str) -> None:
        """Update specific view."""
        views = {
            'overview': self.generate_memory_md,
            'tasks': self.generate_task_view,
            'decisions': self.generate_decision_view,
            'blockers': self.generate_blocker_view,
            'projects': self.generate_project_view
        }
        
        if view in views:
            views[view]()
    
    def get_preview(self, view: str = "overview") -> str:
        """Get preview of dashboard view."""
        if view == "overview":
            return self._generate_overview_preview()
        elif view == "tasks":
            return self._generate_tasks_preview()
        elif view == "decisions":
            return self._generate_decisions_preview()
        elif view == "blockers":
            return self._generate_blockers_preview()
        elif view == "projects":
            return self._generate_projects_preview()
        return ""
    
    def generate_memory_md(self, output_path: str = "MEMORY.md") -> str:
        """Generate main MEMORY.md dashboard."""
        today = datetime.now().strftime('%Y-%m-%d')
        stats = self.db.get_stats()
        
        content = f"""# 🧠 Memory Dashboard

*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*

---

## 📊 Quick Stats

| Metric | Count |
|--------|-------|
| Total Entries | {stats['total_entries']} |
| 🟢 Active Tasks | {stats['active_tasks']} |
| ✅ Completed Tasks | {stats['completed_tasks']} |
| 📋 Active Decisions | {stats['active_decisions']} |
| 🚧 Active Blockers | {stats['active_blockers']} |
| 📁 Projects | {stats['total_projects']} |

---

## 🎯 Today's Focus

{self._generate_today_section()}

---

## 🚀 Active Projects

{self._generate_projects_section()}

---

## ⚡ In Progress

{self._generate_tasks_section(status='in_progress', limit=10)}

---

## 📋 Recent Decisions

{self._generate_decisions_section(limit=5)}

---

## 🚧 Current Blockers

{self._generate_blockers_section(limit=5)}

---

## 📅 Recent Entries

{self._generate_entries_section(limit=7)}

---

## 🔗 Quick Links

- [All Entries](data/entries/)
- [All Projects](data/projects/)
- [Decision Registry](data/decisions/)
- [Generated Reports](reports/)

---

*Generated by Memory Manager v1.0*
"""
        
        with open(output_path, 'w') as f:
            f.write(content)
        
        return output_path
    
    def generate_task_view(self, output_path: str = "data/views/tasks.md") -> None:
        """Generate task dashboard view."""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        
        content = f"""# Task Dashboard

*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*

## Summary

{self._generate_task_summary()}

## Pending Tasks

{self._generate_tasks_section(status='pending', limit=20)}

## In Progress

{self._generate_tasks_section(status='in_progress', limit=20)}

## Blocked Tasks

{self._generate_tasks_section(status='blocked', limit=20)}

## Recently Completed

{self._generate_tasks_section(status='completed', limit=10)}
"""
        
        with open(output_path, 'w') as f:
            f.write(content)
    
    def generate_decision_view(self, output_path: str = "data/views/decisions.md") -> None:
        """Generate decision dashboard view."""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        
        content = f"""# Decision Registry

*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*

## Active Decisions

{self._generate_decisions_section(status='active', limit=20)}

## Decisions Requiring Review

{self._generate_decisions_for_review()}

## Superseded Decisions

{self._generate_decisions_section(status='superseded', limit=10)}
"""
        
        with open(output_path, 'w') as f:
            f.write(content)
    
    def generate_blocker_view(self, output_path: str = "data/views/blockers.md") -> None:
        """Generate blocker dashboard view."""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        
        escalated = self.db.get_escalated_blockers(min_level=1)
        
        content = f"""# Blocker Dashboard

*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*

## Escalated Blockers

{self._generate_escalated_blockers_section()}

## Active Blockers

{self._generate_blockers_section(status='active', limit=20)}

## Resolved Blockers (Last 30 Days)

{self._generate_resolved_blockers_section()}
"""
        
        with open(output_path, 'w') as f:
            f.write(content)
    
    def generate_project_view(self, output_path: str = "data/views/projects.md") -> None:
        """Generate project dashboard view."""
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        
        content = f"""# Project Dashboard

*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*

## Active Projects

{self._generate_projects_section(status='active')}

## Paused Projects

{self._generate_projects_section(status='paused')}

## Recently Completed

{self._generate_projects_section(status='completed')}
"""
        
        with open(output_path, 'w') as f:
            f.write(content)
    
    # Section generators
    
    def _generate_stats_section(self) -> str:
        """Generate statistics table."""
        stats = self.db.get_stats()
        return f"""
| Metric | Count |
|--------|-------|
| Total Entries | {stats['total_entries']} |
| Active Tasks | {stats['active_tasks']} |
| Completed Tasks | {stats['completed_tasks']} |
| Active Decisions | {stats['active_decisions']} |
| Active Blockers | {stats['active_blockers']} |
| Projects | {stats['total_projects']} |
"""
    
    def _generate_today_section(self) -> str:
        """Generate today's focus section."""
        today = datetime.now().strftime('%Y-%m-%d')
        entry = self.db.get_entry(today)
        
        if entry:
            tasks = [t for t in entry.tasks if t.status != 'completed']
            if tasks:
                return "\n".join([f"- [ ] {t.title}" for t in tasks[:5]])
            return "_No tasks for today_"
        
        return f"_No entry for {today}. Create one with:_\n\n`memory-manager.py entry create`"
    
    def _generate_projects_section(self, status: str = 'active') -> str:
        """Generate projects section."""
        projects = self.db.list_projects(status=status, limit=10)
        
        if not projects:
            return "_No projects_"
        
        lines = []
        for p in projects:
            # Calculate progress
            tasks = self.db.list_tasks(project=p.id, limit=1000)
            total = len(tasks)
            completed = len([t for t in tasks if t.status == 'completed'])
            progress = (completed / max(total, 1)) * 100
            
            progress_bar_visual = "█" * int(progress / 10) + "░" * (10 - int(progress / 10))
            
            lines.append(f"- **{p.name}** - {progress_bar_visual} {progress:.0f}%")
            lines.append(f"  Status: {p.status} | Priority: {p.priority}")
            if p.description:
                lines.append(f"  {p.description[:80]}...")
        
        return "\n".join(lines)
    
    def _generate_tasks_section(self, status: str = 'in_progress', limit: int = 10) -> str:
        """Generate tasks section."""
        tasks = self.db.list_tasks(status=status, limit=limit)
        
        if not tasks:
            return "_No tasks_"
        
        lines = []
        for t in tasks:
            priority_emoji = {'high': '🔴', 'medium': '🟡', 'low': '🟢', 'critical': '⛔'}.get(t.priority, '⚪')
            status_emoji = {'completed': '✅', 'in_progress': '▶️', 'blocked': '🚫', 'pending': '⏳'}.get(t.status, '❓')
            lines.append(f"- {priority_emoji} {status_emoji} **{t.title}**")
            if t.description:
                lines.append(f"  {t.description[:60]}...")
        
        return "\n".join(lines)
    
    def _generate_task_summary(self) -> str:
        """Generate task summary."""
        pending = len(self.db.list_tasks(status='pending', limit=1000))
        in_progress = len(self.db.list_tasks(status='in_progress', limit=1000))
        blocked = len(self.db.list_tasks(status='blocked', limit=1000))
        completed = len(self.db.list_tasks(status='completed', limit=1000))
        
        total = pending + in_progress + blocked + completed
        
        if total == 0:
            return "_No tasks_"
        
        return f"""
- **Total:** {total}
- **Pending:** {pending}
- **In Progress:** {in_progress}
- **Blocked:** {blocked}
- **Completed:** {completed}

{progress_bar(completed, total)} Complete
"""
    
    def _generate_decisions_section(self, status: str = 'active', limit: int = 5) -> str:
        """Generate decisions section."""
        decisions = self.db.list_decisions(status=status, limit=limit)
        
        if not decisions:
            return "_No decisions_"
        
        lines = []
        for d in decisions:
            rev_emoji = {'low': '🔄', 'medium': '↩️', 'high': '🔒'}.get(d.reversibility, '❓')
            lines.append(f"- {rev_emoji} **{d.title}**")
            lines.append(f"  Decision: {d.decision}")
            if d.context:
                lines.append(f"  Context: {d.context[:60]}...")
        
        return "\n".join(lines)
    
    def _generate_decisions_for_review(self) -> str:
        """Generate decisions requiring review section."""
        decisions = self.db.get_decisions_for_review(days=30)
        
        if not decisions:
            return "_No decisions due for review_"
        
        lines = []
        for d in decisions:
            review_date = format_date(d.review_date) if d.review_date else "Unknown"
            lines.append(f"- 📅 **{d.title}** - Review by: {review_date}")
        
        return "\n".join(lines)
    
    def _generate_blockers_section(self, status: str = 'active', limit: int = 5) -> str:
        """Generate blockers section."""
        blockers = self.db.list_blockers(status=status, limit=limit)
        
        if not blockers:
            return "_No blockers_"
        
        lines = []
        for b in blockers:
            severity_emoji = {'critical': '🔴', 'high': '🟠', 'medium': '🟡', 'low': '🟢'}.get(b.severity, '⚪')
            esc_indicator = f" ⬆️{b.escalation_level}" if b.escalation_level > 0 else ""
            lines.append(f"- {severity_emoji} **{b.title}**{esc_indicator}")
            if b.description:
                lines.append(f"  {b.description[:60]}...")
        
        return "\n".join(lines)
    
    def _generate_escalated_blockers_section(self) -> str:
        """Generate escalated blockers section."""
        blockers = self.db.get_escalated_blockers(min_level=1)
        
        if not blockers:
            return "_No escalated blockers_"
        
        lines = []
        for b in blockers:
            level_names = {0: "Identified", 1: "Acknowledged", 2: "Escalated", 3: "Critical"}
            level_name = level_names.get(b.escalation_level, "Unknown")
            lines.append(f"- ⬆️**{level_name} (Level {b.escalation_level})**: {b.title}")
        
        return "\n".join(lines)
    
    def _generate_resolved_blockers_section(self) -> str:
        """Generate recently resolved blockers section."""
        from datetime import datetime, timedelta
        
        thirty_days_ago = (datetime.now() - timedelta(days=30)).isoformat()
        blockers = self.db.list_blockers(status='resolved', limit=10)
        
        # Filter to last 30 days
        recent = [b for b in blockers if b.resolved_at and b.resolved_at > thirty_days_ago]
        
        if not recent:
            return "_No recently resolved blockers_"
        
        lines = []
        for b in recent:
            lines.append(f"- ✅ **{b.title}**")
            if b.resolution:
                lines.append(f"  Resolution: {b.resolution[:60]}...")
        
        return "\n".join(lines)
    
    def _generate_entries_section(self, limit: int = 7) -> str:
        """Generate recent entries section."""
        entries = self.db.list_entries(limit=limit)
        
        if not entries:
            return "_No entries_"
        
        lines = []
        for e in entries:
            date_str = format_date(e.date)
            task_count = len(e.tasks)
            decision_count = len(e.decisions)
            lines.append(f"- **{date_str}**: {e.summary.title}")
            if task_count or decision_count:
                details = []
                if task_count:
                    details.append(f"{task_count} tasks")
                if decision_count:
                    details.append(f"{decision_count} decisions")
                lines.append(f"  ({', '.join(details)})")
        
        return "\n".join(lines)
    
    # Preview generators for CLI
    
    def _generate_overview_preview(self) -> str:
        """Generate overview preview."""
        stats = self.db.get_stats()
        return f"""
{Colors.BOLD}Overview Preview{Colors.ENDC}

Stats:
  Entries:    {stats['total_entries']}
  Tasks:      {stats['active_tasks']} active, {stats['completed_tasks']} completed
  Decisions:  {stats['active_decisions']} active
  Blockers:   {stats['active_blockers']} active
  Projects:   {stats['total_projects']}

Today's Focus: {self._generate_today_section()[:100]}...
"""
    
    def _generate_tasks_preview(self) -> str:
        """Generate tasks preview."""
        return self._generate_task_summary()
    
    def _generate_decisions_preview(self) -> str:
        """Generate decisions preview."""
        decisions = self.db.list_decisions(status='active', limit=5)
        lines = [f"{Colors.BOLD}Active Decisions:{Colors.ENDC}"]
        for d in decisions:
            lines.append(f"  - {d.title}")
        return "\n".join(lines)
    
    def _generate_blockers_preview(self) -> str:
        """Generate blockers preview."""
        blockers = self.db.list_blockers(status='active', limit=5)
        lines = [f"{Colors.BOLD}Active Blockers:{Colors.ENDC}"]
        for b in blockers:
            esc = f" [L{b.escalation_level}]" if b.escalation_level > 0 else ""
            lines.append(f"  - {b.title}{esc}")
        return "\n".join(lines)
    
    def _generate_projects_preview(self) -> str:
        """Generate projects preview."""
        projects = self.db.list_projects(status='active', limit=5)
        lines = [f"{Colors.BOLD}Active Projects:{Colors.ENDC}"]
        for p in projects:
            lines.append(f"  - {p.name} ({p.status})")
        return "\n".join(lines)
